### ISSUE TITLE
Update get location swagger endpoint

### ISSUE THREAD

**Issue by d-vucetic** [vegaitglobal/udruzenje-paraplegicara-podgorica-website#8]
Swagger treba da sadrzi sve get parametre da bi front vidio kako da ih salje

**Comment by LjSamardzic** [comment]
Zar ne sadrži? 
![image](https://github.com/vegaitglobal/udruzenje-paraplegicara-podgorica-website/assets/110813413/cfb47ad3-7342-494f-8fe7-51bc634e3014)

**Comment by d-vucetic** [comment]
Izvinite

**Comment by d-vucetic** [comment]
Opet
